version: '3.8'
services:
  server:
    image: azuna-server
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "1337:1337"
   
  client:
    image: azuna-client
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    depends_on:
      - server


